In [3]:
audi = ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A6 e-tron', 'A7', 'A8']

In [4]:
audi

['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A6 e-tron', 'A7', 'A8']

In [5]:
import numpy as np

In [12]:
arr = np.array(audi) # 1 d

In [7]:
arr

array(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A6 e-tron', 'A7', 'A8'],
      dtype='<U9')

In [8]:
my_matrics = [[2, 4, 6, 8, 10, 12], ['A', 'B', 'C', 'D', 'E', 'F'], [1, 3, 5, 7, 9, 11]]

In [9]:
my_matrics

[[2, 4, 6, 8, 10, 12], ['A', 'B', 'C', 'D', 'E', 'F'], [1, 3, 5, 7, 9, 11]]

In [14]:
lst_matr = np.array(my_matrics) # 2 d

In [11]:
lst_matr

array([['2', '4', '6', '8', '10', '12'],
       ['A', 'B', 'C', 'D', 'E', 'F'],
       ['1', '3', '5', '7', '9', '11']], dtype='<U21')

In [15]:
# numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)
np.arange(0, 21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [16]:
np.arange(0, 25, 2) # step=2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [17]:
np.arange(0, 25, 3) # step = 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [19]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((3, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
np.ones((3, 5, 4)) # 3 lists, each list is 5 time ones and each 4 ones 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [32]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
np.linspace(0, 4, 9)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [35]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [36]:
np.linspace(0, 5, 30)

array([0.        , 0.17241379, 0.34482759, 0.51724138, 0.68965517,
       0.86206897, 1.03448276, 1.20689655, 1.37931034, 1.55172414,
       1.72413793, 1.89655172, 2.06896552, 2.24137931, 2.4137931 ,
       2.5862069 , 2.75862069, 2.93103448, 3.10344828, 3.27586207,
       3.44827586, 3.62068966, 3.79310345, 3.96551724, 4.13793103,
       4.31034483, 4.48275862, 4.65517241, 4.82758621, 5.        ])

In [38]:
np.linspace(0, 8, 20)

array([0.        , 0.42105263, 0.84210526, 1.26315789, 1.68421053,
       2.10526316, 2.52631579, 2.94736842, 3.36842105, 3.78947368,
       4.21052632, 4.63157895, 5.05263158, 5.47368421, 5.89473684,
       6.31578947, 6.73684211, 7.15789474, 7.57894737, 8.        ])

In [39]:
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
# random.rand(d0, d1, ..., dn)
np.random.rand(8)

array([0.10933475, 0.96003906, 0.69970174, 0.2208201 , 0.52783614,
       0.13796786, 0.76755755, 0.42746432])

In [45]:
np.random.rand(4, 7)

array([[0.62842735, 0.12180966, 0.07226791, 0.30985937, 0.86352082,
        0.26495073, 0.67036005],
       [0.60679329, 0.39945137, 0.18068046, 0.30007917, 0.18429884,
        0.99472618, 0.71308075],
       [0.95050887, 0.29432063, 0.13126784, 0.74402319, 0.59693945,
        0.53831745, 0.69199272],
       [0.27939627, 0.96109065, 0.65363964, 0.86238224, 0.03049687,
        0.93195716, 0.50120053]])

In [46]:
np.random.randn(4)

array([-0.59963308, -0.7242329 , -0.02817481, -0.01528239])

In [47]:
np.random.randn(3)

array([-1.02219306,  0.82352413, -0.19124786])

In [48]:
np.random.randn(2)

array([ 0.83953696, -0.16575303])

In [49]:
np.random.randn(4, 4)

array([[-0.1582747 , -1.35183615,  1.15349457,  0.95816614],
       [-0.00929323,  0.34393397,  0.74659487,  0.21777859],
       [-0.62999898, -0.43955016,  0.92227376,  0.9424502 ],
       [-0.30571609, -1.03361119,  1.43973163, -0.28988754]])

In [50]:
# random.randint(low, high=None, size=None, dtype=int)
np.random.randint(4)

2

In [53]:
np.random.randint((3, 10))

array([2, 6])

In [55]:
np.random.randint(3, 10, 40)

array([3, 6, 8, 7, 5, 3, 4, 4, 7, 4, 8, 8, 4, 4, 4, 7, 6, 8, 9, 5, 6, 5,
       9, 8, 9, 7, 5, 7, 9, 4, 6, 7, 6, 5, 5, 3, 9, 4, 8, 5])

In [56]:
np.random.randint(3, 1000, 40)

array([897, 395, 233, 396, 513,  11,  99, 167, 373, 360,  28,  92, 335,
       535, 656, 442, 728, 406, 335, 798, 335, 975, 875, 317, 205, 563,
       453, 434, 569, 709, 869, 427,  82, 275, 170, 148,  93, 542, 229,
       885])

In [58]:
ar = np.arange(9)

In [59]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
ranar = np.random.randint(5, 50, 20)

In [62]:
ranar

array([41, 26, 18, 20, 16, 37, 27, 43, 41, 33, 36, 38, 15, 44, 35, 41, 34,
       19, 43, 38])

In [69]:
# numpy.reshape(a, /, shape, order='C', *, copy=None)[source]
ar.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
num = np.arange(20)

In [77]:
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
num.reshape(5, 4) # it must be between 20 because num is setup to 20

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [83]:
ranar

array([41, 26, 18, 20, 16, 37, 27, 43, 41, 33, 36, 38, 15, 44, 35, 41, 34,
       19, 43, 38])

In [84]:
ranar.max()

np.int64(44)

In [85]:
ranar.min()

np.int64(15)

In [86]:
ranar

array([41, 26, 18, 20, 16, 37, 27, 43, 41, 33, 36, 38, 15, 44, 35, 41, 34,
       19, 43, 38])

In [88]:
ranar.argmax() # retrive the the maximum 44 in the index 13

np.int64(13)

In [89]:
ranar

array([41, 26, 18, 20, 16, 37, 27, 43, 41, 33, 36, 38, 15, 44, 35, 41, 34,
       19, 43, 38])

In [90]:
ranar.argmin() # retrive the minum number which is 15 in the index 12 

np.int64(12)

In [93]:
ranar.shape

(20,)

In [96]:
dill = ranar.reshape(5, 4) 

In [97]:
dill

array([[41, 26, 18, 20],
       [16, 37, 27, 43],
       [41, 33, 36, 38],
       [15, 44, 35, 41],
       [34, 19, 43, 38]])

In [98]:
dill.shape

(5, 4)

In [101]:
ranar.dtype

dtype('int64')

In [102]:
dill.dtype

dtype('int64')

In [104]:
ar.dtype

dtype('int64')

In [105]:
from numpy.random import randint

In [106]:
randint(7, 40)

10

In [107]:
randint(7, 40)

8